projectTodo/appTodo/urls.py
from . import views
from django.urls import path
app_name = 'appTodo'

urlpatterns = [
    path('',views.todo, name='todo'),
    path('delete/<int:task_id>/',views.delete, name='delete'),
    path('update/<int:task_id>/',views.update, name='update'),
    path('cbvhome/', views.listview_task.as_view(), name='cbvhome'),
    path('cbvdetail/<int:pk>/', views.detailview_task.as_view(), name='cbvdetail'),
    path('cbvupdate/<int:pk>/', views.updateview_task.as_view(), name='cbvupdate'),
    path('cbvdelete/',views.deleteview_task.as_view(), name='cbvdelete')
]

projectTodo/projectTodo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('appTodo.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

projectTodo/appTodo/models.py
from django.db import models

# Create your models here.
class task(models.Model):
    name = models.CharField(max_length=150)
    priority = models.IntegerField()
    date = models.DateField()

    def __str__(self):
        return self.name

projectTodo/appTodo/forms.py
from django import forms
from . models import task

class form_task(forms.ModelForm):
    class Meta:
        model = task
        fields =['name','priority','date']

projectTodo/appTodo/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .forms import form_task
from .models import task
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, DeleteView


class listview_task(ListView):
    model = task
    template_name = 'home.html'
    context_object_name = 'model_db'
    fields = ['name', 'priority', 'date']

class detailview_task(DetailView):
    model = task
    template_name = 'details.html'
    context_object_name = 'data'

class updateview_task(UpdateView):
    model = task
    template_name = 'update.html'
    context_object_name = 'data'
    fields = ('name','priority', 'date')

    def get_success_url(self):
        return reverse_lazy('appTodo:cbvdetail',kwargs={'pk':self.object.id})

class deleteview_task(DeleteView):
    model = task
    template_name = 'delete.html'
    succcess_url = reverse_lazy('appTodo:cbvhome')

# Create your views here.
def todo(request):
    model_db = task.objects.all()
    if request.method == "POST":
        name = request.POST.get('name', '')
        priority = request.POST.get('priority')
        date = request.POST.get('task_date')

        model = task(name=name,
                     priority=priority,
                     date=date)
        model.save()

    return render(request, 'home.html', {'model_db': model_db})


def delete(request, task_id):
    del_task = task.objects.get(id=task_id)
    if request.method == "POST":
        del_task.delete()
        return redirect('/')
    return render(request, 'delete.html')


def update(request, task_id):
    task_update = task.objects.get(id=task_id)
    form_update = form_task(request.POST or None,
                     request.FILES,
                     instance=task_update)

    if form_update.is_valid():
        print("Form is valid")
        form_update.save()
        return redirect("/")
    return render(request, 'edit.html', {'form': form_update, 'task': task_update})

projectTodo/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

projectTodo/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form method ="POST">
    {% csrf_token %}
    <p>Do you want to delete this task</p>
    <input type="submit">
</form>
{% endblock %}

projectTodo/templates/details.html
{% extends 'base.html' %}
{% block content %}


<center>
<div class="col-md-6">
    <table class="table shadow">
        <thead>
        <tr>
            <th scope="col">Task Name</th>
            <th scope="col">Priority</th>
            <th scope="col">Date</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{data.name}}</td>
            <td>{{data.priority}}</td>
            <td>{{data.date}}</td>
        </tr>
        </tbody>
    </table>
    <td><a href="{% url 'appTodo:cbvhome' %}" class="btn btn-danger">Home</a></td>
</div>
</center>

{% endblock %}

projectTodo/templates/edit.html
<html>
<body>
<form method="POST" >
  {% csrf_token %}
  {{form.as_p}}
  <p>Date format (mm/dd/yyyy)</p>
  <input type="submit">
</form>
</body>
</html>

projectTodo/templates/home.html
{% extends 'base.html' %}
{% block content %}
<style>
    body
{
    counter-reset: Serial;
}

tr td:first-child:before
{
  counter-increment: Serial;
  content: counter(Serial);
}
</style>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>TODO</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
        <form method="POST" class="p-3 shadow">
           {% csrf_token %}
            <div class="form-group">
                <label for="task_name" class="form-label">Task Name:</label>
                <input type="text" class="form-control" id="task_name" name="name">
            </div>
            <div class="form-group">
                <label for="task_name" class="form-label">Priority:</label>
                <input type="number" class="form-control" name="priority">
            </div>
            <div class="form-group">
                <label for="task_date" class="form-label">Date:</label>
                <input type="date" id="task_date" class="form-control" name="task_date" style="margin-bottom:20px;">
            </div>
            <input type="submit" class="btn btn-primary">
        </form>
        </div>
        <div class="col-md-6">
            <table class="table shadow">
                <thead>
                <tr>
                    <th scope="col">Sl. No</th>
                    <th scope="col">Task Name</th>
                    <th scope="col">Priority</th>
                    <th scope="col">Date</th>
                    <th scope="col" colspan="2" style="text-align:center;">Action</th>
                </tr>
                </thead>
                {% for i in model_db %}
                <tbody>
                <tr>
                    <td scope="row"></td>
                    <td><a href="{% url 'appTodo:cbvdetail' i.id %}">{{i.name}}</a></td>
                    <td>{{i.priority}}</td>
                    <td>{{i.date}}</td>
                    <td><a href="{% url 'appTodo:delete' i.id %}" class="btn btn-danger">Delete</a></td>
                    <td><a href="{% url 'appTodo:cbvupdate' i.id %}" class="btn btn-success">Update</a></td>
                </tr>
                </tbody>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

projectTodo/templates/home_initial.html
{% extends 'base.html' %}
{% block content %}
<style>
    body
{
    counter-reset: Serial;
}

tr td:first-child:before
{
  counter-increment: Serial;
  content: counter(Serial);
}
</style>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>TODO</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
        <form method="POST" class="p-3 shadow">
           {% csrf_token %}
            <div class="form-group">
                <label for="task_name" class="form-label">Task Name:</label>
                <input type="text" class="form-control" id="task_name" name="name">
            </div>
            <div class="form-group">
                <label for="task_name" class="form-label">Priority:</label>
                <input type="number" class="form-control" name="priority">
            </div>
            <div class="form-group">
                <label for="task_date" class="form-label">Date:</label>
                <input type="date" id="task_date" class="form-control" name="task_date" style="margin-bottom:20px;">
            </div>
            <input type="submit" class="btn btn-primary">
        </form>
        </div>
        <div class="col-md-6">
            <table class="table shadow">
                <thead>
                <tr>
                    <th scope="col">Sl. No</th>
                    <th scope="col">Task Name</th>
                    <th scope="col">Priority</th>
                    <th scope="col">Date</th>
                    <th scope="col" colspan="2" style="text-align:center;">Action</th>
                </tr>
                </thead>
                {% for i in model_db %}
                <tbody>
                <tr>
                    <td scope="row"></td>
                    <td><a href="{% url 'appTodo:cbvdetail' i.id %}">{{i.name}}</a></td>
                    <td>{{i.priority}}</td>
                    <td>{{i.date}}</td>
                    <td><a href="{% url 'appTodo:delete' i.id %}" class="btn btn-danger">Delete</a></td>
                    <td><a href="{% url 'appTodo:update' i.id %}" class="btn btn-success">Update</a></td>
                </tr>
                </tbody>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

projectTodo/templates/update.html
{% extends 'base.html' %}
{% block content %}
<center>
<form method="post">
    {% csrf_token %}
  <div class="form-group">
      <table>
          {{form.as_table}}
      </table>
      <p>Date format (yyyy/mm/dd)</p>
      <input type="submit">
  </div>
</form>
</center>
{% endblock %}